//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `Tag.json`.
    static let tagJson = Rswift.FileResource(bundle: R.hostingBundle, name: "Tag", pathExtension: "json")
    
    /// `bundle.url(forResource: "Tag", withExtension: "json")`
    static func tagJson(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.tagJson
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 7 images.
  struct image {
    /// Image `active`.
    static let active = Rswift.ImageResource(bundle: R.hostingBundle, name: "active")
    /// Image `clear`.
    static let clear = Rswift.ImageResource(bundle: R.hostingBundle, name: "clear")
    /// Image `negative`.
    static let negative = Rswift.ImageResource(bundle: R.hostingBundle, name: "negative")
    /// Image `normal`.
    static let normal = Rswift.ImageResource(bundle: R.hostingBundle, name: "normal")
    /// Image `off`.
    static let off = Rswift.ImageResource(bundle: R.hostingBundle, name: "off")
    /// Image `on`.
    static let on = Rswift.ImageResource(bundle: R.hostingBundle, name: "on")
    /// Image `positive`.
    static let positive = Rswift.ImageResource(bundle: R.hostingBundle, name: "positive")
    
    /// `UIImage(named: "active", bundle: ..., traitCollection: ...)`
    static func active(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.active, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "clear", bundle: ..., traitCollection: ...)`
    static func clear(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.clear, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "negative", bundle: ..., traitCollection: ...)`
    static func negative(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.negative, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "normal", bundle: ..., traitCollection: ...)`
    static func normal(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.normal, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "off", bundle: ..., traitCollection: ...)`
    static func off(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.off, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "on", bundle: ..., traitCollection: ...)`
    static func on(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.on, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "positive", bundle: ..., traitCollection: ...)`
    static func positive(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.positive, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 2 nibs.
  struct nib {
    /// Nib `Cell`.
    static let cell = _R.nib._Cell()
    /// Nib `TagViewCell`.
    static let tagViewCell = _R.nib._TagViewCell()
    
    /// `UINib(name: "Cell", in: bundle)`
    static func cell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.cell)
    }
    
    /// `UINib(name: "TagViewCell", in: bundle)`
    static func tagViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.tagViewCell)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 2 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `Cell`.
    static let cell: Rswift.ReuseIdentifier<Cell> = Rswift.ReuseIdentifier(identifier: "Cell")
    /// Reuse identifier `TagViewCell`.
    static let tagViewCell: Rswift.ReuseIdentifier<TagViewCell> = Rswift.ReuseIdentifier(identifier: "TagViewCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `CreateTagViewController`.
    static let createTagViewController = _R.storyboard.createTagViewController()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "CreateTagViewController", bundle: ...)`
    static func createTagViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.createTagViewController)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _TagViewCell.validate()
    }
    
    struct _Cell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = Cell
      
      let bundle = R.hostingBundle
      let identifier = "Cell"
      let name = "Cell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> Cell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? Cell
      }
      
      fileprivate init() {}
    }
    
    struct _TagViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType, Rswift.Validatable {
      typealias ReusableType = TagViewCell
      
      let bundle = R.hostingBundle
      let identifier = "TagViewCell"
      let name = "TagViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> TagViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? TagViewCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "positive", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'positive' is used in nib 'TagViewCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "off", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'off' is used in nib 'TagViewCell', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try main.validate()
      try createTagViewController.validate()
    }
    
    struct createTagViewController: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = CreateTagViewController
      
      let bundle = R.hostingBundle
      let createTagViewController = StoryboardViewControllerResource<CreateTagViewController>(identifier: "CreateTagViewController")
      let name = "CreateTagViewController"
      
      func createTagViewController(_: Void = ()) -> CreateTagViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: createTagViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "clear") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'clear' is used in storyboard 'CreateTagViewController', but couldn't be loaded.") }
        if UIKit.UIImage(named: "active") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'active' is used in storyboard 'CreateTagViewController', but couldn't be loaded.") }
        if _R.storyboard.createTagViewController().createTagViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'createTagViewController' could not be loaded from storyboard 'CreateTagViewController' as 'CreateTagViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = ViewController
      
      let bundle = R.hostingBundle
      let name = "Main"
      
      static func validate() throws {
        if UIKit.UIImage(named: "active") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'active' is used in storyboard 'Main', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
